(() => {
  "use strict";
  const TYPES=[{id:"cat",name:"ネコ",score:100},{id:"dog",name:"犬",score:150},{id:"deer",name:"シカ",score:300},{id:"cow",name:"牛",score:500}];
  const HUMAN_TYPES=[{id:"human_farmer",name:"農夫",score:1000},{id:"human_schoolgirl",name:"女子高生",score:1000},{id:"human_worker",name:"サラリーマン",score:1000},{id:"human_student",name:"眼鏡の学生",score:1000},{id:"human_grandpa",name:"お爺さん",score:1000},{id:"human_grandma",name:"お婆さん",score:1000},{id:"human_ol",name:"OL",score:1000},{id:"human_child",name:"子供",score:1000}];
  const ids=["game","scene","ufo","beam","objects","score","stage","backgroundBase","backgroundOverlay","controlKey","instruction","subtext","phaseBadge","toast","flash","particles","target-line-x","target-line-y","reticle","startButton","trackName","bgmToggle","seToggle","ending","creditsRoll","endingActions","replayCredits","restartGame"];
  const els=Object.fromEntries(ids.map(id=>[id.replaceAll("-","_"),document.getElementById(id)]));
  let score=0,stage=1,stageUnitCount=6,phase="vertical",x=7,y=88,previousTime=performance.now(),critters=[],roundTimer=null,audioContext=null,currentFrame=-1,altSpriteMode=true,bgmEnabled=true,seEnabled=true,advancingStage=false,backgroundIndex=0,backgroundStep=0,scoreAnimationId=0,endingMode=false;
  let playStats={plays:0,successes:0,failures:0,nearMisses:0,caught:[],counts:{}};
  const ufoFloat=els.ufo.querySelector(".ufo-float");
  const touchMode=matchMedia("(pointer: coarse)").matches;
  let pointerActive=false,lastTouchInputAt=0,lastInteractionAt=performance.now();
  const IDLE_BACKGROUND_INTERVAL=60000;
  const uiSelector="button,input,textarea,select,a,[role='button'],[contenteditable='true'],dialog";
  const isUIEvent=event=>Boolean(event.target.closest?.(uiSelector));
  const noteInteraction=()=>{lastInteractionAt=performance.now()};
  const bgmTracks=[
    {title:"青い光のランデブー",src:"assets/sounds/bgm.mp3"},
    {title:"キノコは宇宙人だという事が判明",src:"assets/sounds/mushroom-alien.mp3"}
  ];
  const endingTrack={title:"青い光のランデブー Avant Garde Pop ver.",src:"assets/sounds/ending.mp3"};
  const resultSettings=window.UNIT_RESULT_SETTINGS||{};
  let bgmTrackIndex=0;
  const bgm=new Audio(bgmTracks[bgmTrackIndex].src);bgm.loop=false;bgm.volume=.34;
  const animalVoiceFiles={cat:"assets/sounds/cat.mp3",dog:"assets/sounds/dog.mp3",deer:"assets/sounds/deer.mp3",cow:"assets/sounds/cow.mp3",human_farmer:"assets/sounds/human-farmer.mp3",human_schoolgirl:"assets/sounds/human-schoolgirl.mp3",human_worker:"assets/sounds/human-worker.mp3",human_student:"assets/sounds/human-student.mp3",human_grandpa:"assets/sounds/human-grandpa.mp3",human_grandma:"assets/sounds/human-grandma.mp3",human_ol:"assets/sounds/human-ol.mp3",human_child:"assets/sounds/human-child.mp3"};
  const ufoMoveSound=new Audio("assets/sounds/ufo-move.mp3");ufoMoveSound.volume=.72;
  const scoreAddSound=new Audio("assets/sounds/score-add.mp3");scoreAddSound.volume=.72;
  const activeAnimalSounds=new Set();
  const spriteImageCache=[];
  const backgrounds=["assets/background/day.png","assets/background/evening.png","assets/background/night.png"],backgroundNames=["昼","夕方","夜"];
  // 背景画像上で陸地に当たる地点だけを登録する。
  const LAND_SPOTS=[[39,24],[43,23],[47,25],[52,27],[58,28],[64,30],[71,31],[78,34],[17,61],[21,56],[23,52],[24,59],[29,57],[30,54],[31,49],[33,58],[34,47],[36,39],[36,53],[39,36],[39,48],[41,58],[42,45],[43,50],[45,29],[46,47],[47,42],[48,53],[49,58],[52,35],[53,55],[54,46],[56,30],[57,58],[58,52],[59,36],[61,51],[62,55],[65,44],[66,47],[68,48],[69,42],[70,34],[73,36],[75,52],[77,48],[10,70],[14,76],[20,73],[44,67],[50,68],[56,65]];
  const CAPTURE_ZONES={center:2.1,ring:4,beam:7.5};
  const TARGET_BOUNDS={minY:touchMode?23:19,maxY:88,maxX:92};
  const spawnDebug=document.createElement("div");spawnDebug.className="spawn-debug";spawnDebug.setAttribute("aria-hidden","true");spawnDebug.innerHTML=`<b>SPAWN AREA</b>${LAND_SPOTS.map(([spotX,spotY])=>`<i style="left:${spotX}%;top:${spotY}%"></i>`).join("")}`;els.scene.append(spawnDebug);

  function tone(frequency,duration=.08,volume=.045,type="sine",delay=0){
    if(!seEnabled)return;
    try{audioContext||=new(window.AudioContext||window.webkitAudioContext)();const oscillator=audioContext.createOscillator(),gain=audioContext.createGain(),now=audioContext.currentTime+delay;oscillator.type=type;oscillator.frequency.setValueAtTime(frequency,now);gain.gain.setValueAtTime(.001,now);gain.gain.linearRampToValueAtTime(volume,now+.01);gain.gain.exponentialRampToValueAtTime(.001,now+duration);oscillator.connect(gain).connect(audioContext.destination);oscillator.start(now);oscillator.stop(now+duration+.02)}catch(_){/* 音声が利用できなくてもゲームは継続 */}
  }
  const playDecision=()=>{tone(520,.07,.035,"square");tone(760,.09,.025,"square",.07)};
  const playBeam=()=>[110,150,210,290].forEach((f,i)=>tone(f,.65,.035,"sawtooth",i*.06));
  const playSuccess=()=>[440,660,880].forEach((f,i)=>tone(f,.15,.04,"sine",i*.1));
  function playBGM(){if(bgmEnabled&&bgm.paused)bgm.play().catch(()=>{/* ブラウザの自動再生制限時は次の操作で再試行 */})}
  function playAnimalVoice(kind){if(!seEnabled||!animalVoiceFiles[kind])return;const sound=new Audio(animalVoiceFiles[kind]);sound.volume=.72;activeAnimalSounds.add(sound);sound.addEventListener("ended",()=>activeAnimalSounds.delete(sound),{once:true});sound.play().catch(()=>activeAnimalSounds.delete(sound))}
  function playUfoMove(){if(!seEnabled)return;ufoMoveSound.currentTime=0;ufoMoveSound.play().catch(()=>{/* 音声が利用できなくてもゲームは継続 */})}
  function playScoreAdd(){if(!seEnabled)return;scoreAddSound.currentTime=0;scoreAddSound.play().catch(()=>{/* 音声が利用できなくてもゲームは継続 */})}
  function updateAudioButtons(){els.bgmToggle.setAttribute("aria-pressed",String(bgmEnabled));els.bgmToggle.setAttribute("aria-label",`BGMを${bgmEnabled?"オフ":"オン"}にする`);els.trackName.textContent=`♪：${bgmEnabled?(endingMode?endingTrack.title:bgmTracks[bgmTrackIndex].title):"BGM停止中"}`;els.trackName.classList.toggle("paused",!bgmEnabled);els.seToggle.setAttribute("aria-pressed",String(seEnabled));els.seToggle.setAttribute("aria-label",`効果音を${seEnabled?"オフ":"オン"}にする`);els.seToggle.querySelector("span").textContent=seEnabled?"🔊":"🔇"}
  function nightAmount(){const next=(backgroundIndex+1)%backgrounds.length,blend=backgroundStep/10;if(next===2)return blend;if(backgroundIndex===2)return 1-blend;return 0}
  function updateUnitLighting(){els.game.style.setProperty("--unit-brightness",String(1-nightAmount()*.5))}
  function renderBackground(resetOverlay=false){const next=(backgroundIndex+1)%backgrounds.length;els.backgroundBase.style.backgroundImage=`url("${backgrounds[backgroundIndex]}")`;if(resetOverlay){els.backgroundOverlay.style.transition="none";els.backgroundOverlay.style.opacity="0";els.backgroundOverlay.style.backgroundImage=`url("${backgrounds[next]}")`;void els.backgroundOverlay.offsetWidth;els.backgroundOverlay.style.transition="opacity .9s ease";requestAnimationFrame(()=>{els.backgroundOverlay.style.opacity=String(backgroundStep/10)})}else{els.backgroundOverlay.style.backgroundImage=`url("${backgrounds[next]}")`;els.backgroundOverlay.style.opacity=String(backgroundStep/10)}updateUnitLighting()}
  function advanceBackground(debug=false){let resetOverlay=false;if(backgroundStep<10)backgroundStep++;else{backgroundIndex=(backgroundIndex+1)%backgrounds.length;backgroundStep=1;resetOverlay=true}renderBackground(resetOverlay);if(debug){const next=(backgroundIndex+1)%backgrounds.length;showToast(`背景：${backgroundNames[backgroundIndex]} 100% ＋ ${backgroundNames[next]} ${backgroundStep*10}%`);setTimeout(()=>{if(phase!=="result")els.toast.classList.remove("show")},1200)}}
  function advanceIdleBackground(){if(endingMode)return;const now=performance.now(),steps=Math.floor((now-lastInteractionAt)/IDLE_BACKGROUND_INTERVAL);if(steps<1)return;for(let i=0;i<steps;i++)advanceBackground();lastInteractionAt+=steps*IDLE_BACKGROUND_INTERVAL}
  function frameUrl(kind,frame,caught=false){if(kind.startsWith("human_"))return `assets/characters/frames-human/${kind}-${caught?4:(frame-1)%3+1}.png`;if(altSpriteMode)return `assets/characters/frames-alt/${kind}-${caught?4:(frame-1)%3+1}.png`;return `assets/characters/frames/${kind}-${caught?8:frame}.png`}
  function captureChance(item,distance){if(distance<=CAPTURE_ZONES.center)return 1;let chance=distance<=CAPTURE_ZONES.ring ? .75 : .5;if(item.type.id==="cat"||item.type.id==="human_child")chance+=.1;if(item.type.id==="cow")chance-=.1;return Math.max(0,Math.min(1,chance))}
  function preloadActiveSpriteFrames(){const urls=[...TYPES.flatMap(type=>Array.from({length:4},(_,i)=>`assets/characters/frames-alt/${type.id}-${i+1}.png`)),...HUMAN_TYPES.flatMap(type=>Array.from({length:4},(_,i)=>`assets/characters/frames-human/${type.id}-${i+1}.png`))];return Promise.all(urls.map(url=>new Promise(resolve=>{const image=new Image();spriteImageCache.push(image);image.onload=async()=>{try{await image.decode?.()}catch(_){/* 読み込み済みならそのまま使用 */}resolve()};image.onerror=resolve;image.src=url})))}
  function toggleSpriteMode(){altSpriteMode=!altSpriteMode;els.game.classList.toggle("alt-sprites",altSpriteMode);currentFrame=-1;critters.forEach(item=>{const caught=item.el.classList.contains("abducting");item.el.querySelector(".sprite-art").style.backgroundImage=`url("${frameUrl(item.type.id,1,caught)}")`});showToast(altSpriteMode?"4コマ・ドット絵モード":"8コマ・リアルモード");setTimeout(()=>{if(phase!=="result")els.toast.classList.remove("show")},1300)}
  function toggleSpawnDebug(){const shown=spawnDebug.classList.toggle("show");showToast(shown?"配置可能範囲：表示":"配置可能範囲：非表示");setTimeout(()=>{if(phase!=="result")els.toast.classList.remove("show")},1200)}

  function createParticles(){els.particles.innerHTML="";for(let i=0;i<22;i++){const p=document.createElement("i");p.className="particle";p.style.setProperty("--x",`${8+Math.random()*84}%`);p.style.setProperty("--d",`${.65+Math.random()*1.1}s`);p.style.setProperty("--drift",`${-16+Math.random()*32}px`);p.style.animationDelay=`${-Math.random()*1.5}s`;els.particles.append(p)}}

  function spawnCritters(count){
    els.objects.innerHTML="";critters=[];const pool=[],extraAnimal=count%2&&Math.random()<.5?1:0,animalCount=Math.floor(count/2)+extraAnimal,humanCount=count-animalCount;for(let i=0;i<animalCount;i++)pool.push(TYPES[Math.floor(Math.random()*TYPES.length)]);for(let i=0;i<humanCount;i++)pool.push(HUMAN_TYPES[Math.floor(Math.random()*HUMAN_TYPES.length)]);pool.sort(()=>Math.random()-.5);
    const shuffled=[...LAND_SPOTS].sort(()=>Math.random()-.5),spots=Array.from({length:count},(_,i)=>{const base=shuffled[i%shuffled.length],lap=Math.floor(i/shuffled.length),offset=lap?(i%2?.8:-.8):0;return[base[0]+offset,base[1]+(lap?(i%3-1)*.55:0)]});
    spots.forEach(([baseX,baseY],index)=>{const cx=baseX+(Math.random()-.5),cy=baseY+(Math.random()-.5)*.7,type=pool[index],el=document.createElement("div");el.className=`critter critter-${type.id}`;el.dataset.name=type.name;el.dataset.score=type.score;el.style.left=`${cx}%`;el.style.top=`${cy}%`;el.innerHTML=`<span class="sprite sprite-art sprite-${type.id}" data-kind="${type.id}" aria-hidden="true"></span><span class="label">${type.name} ${type.score}</span>`;el.querySelector(".sprite-art").style.backgroundImage=`url("${frameUrl(type.id,1)}")`;els.objects.append(el);critters.push({el,x:cx,y:cy,type})})
  }

  function updateUI(){
    const resultText=advancingStage?["RESULT","次のラウンドを準備中","次のステージへ進みます"]:["RESULT","次のチャレンジへ","まもなく左下から再開します"],content=touchMode?{vertical:["1ST MOVE","タップで奥へ移動","もう一度タップすると停止"],verticalMoving:["1ST MOVE","奥へ移動中…","タップしてストップ"],horizontal:["2ND MOVE","タップで右へ移動","もう一度タップするとキャッチ"],horizontalMoving:["2ND MOVE","右へ移動中…","タップしてキャッチ"],locked:["LOCKED","位置決定！","ビーム発射"],beaming:["ABDUCTION","吸引中…","青白い光の中へ──"],result:resultText}:{vertical:["1ST MOVE","押し続ける","離すと奥行き位置が決定"],verticalMoving:["1ST MOVE","奥へ移動中…","離してストップ"],horizontal:["2ND MOVE","押し続ける","離すと停止して自動でビーム発射"],horizontalMoving:["2ND MOVE","右へ移動中…","離してキャッチ"],locked:["LOCKED","位置決定！","ビーム発射"],beaming:["ABDUCTION","吸引中…","青白い光の中へ──"],result:resultText};if(!content[phase])return;[els.phaseBadge.textContent,els.instruction.textContent,els.subtext.textContent]=content[phase];els.target_line_x.style.top=`${y}%`;els.target_line_y.style.left=`${x}%`;els.target_line_x.classList.toggle("locked",phase!=="vertical"&&phase!=="verticalMoving");els.target_line_y.classList.toggle("locked",phase!=="horizontal"&&phase!=="horizontalMoving")
  }
  function updatePosition(){els.ufo.style.left=`${x-5.5}%`;els.ufo.style.top=`${y-28}%`;els.reticle.style.left=`${x}%`;els.reticle.style.top=`${y}%`;els.target_line_x.style.top=`${y}%`;els.target_line_y.style.left=`${x}%`}
  function resetUfoAppearance(){els.ufo.classList.remove("teleport-out","teleport-in");els.ufo.style.animation="none";els.ufo.style.opacity="1";els.ufo.style.scale="1";els.ufo.style.filter="drop-shadow(0 8px 8px rgba(0,18,30,.7))";els.ufo.style.webkitFilter="drop-shadow(0 8px 8px rgba(0,18,30,.7))";void els.ufo.offsetWidth;els.ufo.style.removeProperty("animation")}
  function showToast(html){els.toast.innerHTML=html;els.toast.classList.add("show")}
  function animateScore(from,to){cancelAnimationFrame(scoreAnimationId);const started=performance.now(),duration=850;els.score.classList.remove("score-rolling");void els.score.offsetWidth;els.score.classList.add("score-rolling");function tick(now){const progress=Math.min(1,(now-started)/duration),stepped=Math.floor(progress*28)/28,eased=1-Math.pow(1-stepped,3),shown=Math.round(from+(to-from)*eased);els.score.textContent=String(shown).padStart(6,"0");if(progress<1)scoreAnimationId=requestAnimationFrame(tick);else{els.score.textContent=String(to).padStart(6,"0");els.score.classList.remove("score-rolling")}}scoreAnimationId=requestAnimationFrame(tick)}
  const percent=(value,total)=>total?`${(value/total*100).toFixed(1)}%`:"0.0%";
  const pick=list=>list?.length?list[Math.floor(Math.random()*list.length)]:"";
  function createUnitProfile(type){const setting=resultSettings[type.id]||{surnames:["エゾ"],names:["タロウ"],lifespan:"1～108",description:"北海道で暮らしていた謎多き存在"},ages=String(setting.lifespan).match(/\d+/g)?.map(Number)||[1,108],min=Math.min(ages[0],ages[1]??ages[0]),max=Math.max(ages[0],ages[1]??ages[0]);return{type,name:[pick(setting.surnames),pick(setting.names)].filter(Boolean).join(" "),age:min+Math.floor(Math.random()*(max-min+1)),description:setting.description}}
  function resultIcon(type){return `<img src="${frameUrl(type.id,1)}" alt="">`}
  function buildCredits(){
    const allTypes=[...TYPES,...HUMAN_TYPES],byId=Object.fromEntries(allTypes.map(type=>[type.id,type]));
    const counts=Object.entries(playStats.counts).filter(([,count])=>count>0).sort((a,b)=>a[1]-b[1]||byId[a[0]].name.localeCompare(byId[b[0]].name,"ja"));
    const countRows=counts.map(([id,count])=>`<li>${resultIcon(byId[id])}<span>${byId[id].name}</span><b>${count}体</b></li>`).join("");
    const detailRows=playStats.caught.map((unit,index)=>`<li>${resultIcon(unit.type)}<span><b>${String(index+1).padStart(3,"0")}　${unit.name}・${unit.age}才</b><small>${unit.description}</small></span></li>`).join("");
    els.creditsRoll.innerHTML=`<h1>PLAY RESULT</h1><p class="ending-stage">STAGE 10 CLEAR</p><section><h2>FINAL SCORE</h2><strong class="final-score">${String(score).padStart(6,"0")}</strong></section><section class="summary"><p><span>総プレイ回数</span><b>${playStats.plays}回</b></p><p><span>キャッチできた合計回数</span><b>${playStats.successes}回　${percent(playStats.successes,playStats.plays)}</b></p><p><span>失敗した合計回数</span><b>${playStats.failures}回　${percent(playStats.failures,playStats.plays)}</b></p><p><span>惜しい！が出た回数</span><b>${playStats.nearMisses}回　${percent(playStats.nearMisses,playStats.plays)}</b></p><p><span>キャッチしたユニット</span><b>${playStats.caught.length}体</b></p></section><section><h2>CAPTURE COUNT</h2><ul class="capture-counts">${countRows}</ul></section><section><h2>ABDUCTION ARCHIVE</h2><ul class="capture-details">${detailRows}</ul></section><div class="credits-thanks">Thank you for playing.</div>`;
    els.creditsRoll.style.setProperty("--credits-duration",`${Math.min(190,Math.max(58,42+playStats.caught.length*.72))}s`);
  }
  function replayCredits(){els.endingActions.classList.remove("show");els.creditsRoll.classList.remove("rolling");void els.creditsRoll.offsetWidth;els.creditsRoll.classList.add("rolling")}
  function startEnding(debug=false){clearTimeout(roundTimer);endingMode=true;phase="ending";buildCredits();els.game.classList.add("ending-mode");els.ending.setAttribute("aria-hidden","false");els.backgroundBase.style.backgroundImage='url("assets/background/result.png")';els.backgroundOverlay.style.opacity="0";els.game.style.setProperty("--unit-brightness","1");bgm.pause();bgm.loop=true;bgm.src=endingTrack.src;bgm.currentTime=0;updateAudioButtons();playBGM();replayCredits();window.dispatchEvent(new CustomEvent("ufo-ending",{detail:{score,catches:playStats.caught.length,debug}}))}
  function restartGame(){clearTimeout(roundTimer);endingMode=false;score=0;stage=1;stageUnitCount=6;backgroundIndex=0;backgroundStep=0;playStats={plays:0,successes:0,failures:0,nearMisses:0,caught:[],counts:{}};els.score.textContent="000000";els.game.classList.remove("ending-mode");els.ending.setAttribute("aria-hidden","true");els.endingActions.classList.remove("show");els.creditsRoll.classList.remove("rolling");bgm.pause();bgm.loop=false;bgmTrackIndex=0;bgm.src=bgmTracks[0].src;bgm.currentTime=0;updateAudioButtons();renderBackground(true);playBGM();startStage();window.dispatchEvent(new Event("ufo-restart"))}
  function startRound(){const teleporting=phase==="result";clearTimeout(roundTimer);els.beam.classList.remove("active","retracting");els.flash.classList.remove("active");els.game.classList.remove("beaming");els.toast.classList.remove("show");critters.forEach(item=>item.el.classList.remove("missed","near-miss","targeted","nice-catch"));advancingStage=false;currentFrame=-1;if(!teleporting){resetUfoAppearance();x=7;y=TARGET_BOUNDS.maxY;phase="vertical";updatePosition();updateUI();return}phase="resetting";playUfoMove();resetUfoAppearance();els.ufo.classList.add("teleport-out");setTimeout(()=>{x=7;y=TARGET_BOUNDS.maxY;updatePosition();resetUfoAppearance();els.ufo.classList.add("teleport-in");setTimeout(()=>{resetUfoAppearance();phase="vertical";updateUI()},420)},320)}
  function startStage(){els.stage.textContent=`STAGE ${stage}`;spawnCritters(stageUnitCount);startRound()}

  function fireBeam(){
    phase="beaming";els.game.classList.add("beaming");ufoFloat.style.backgroundImage='url("assets/characters/frames/ufo-1.png")';els.beam.classList.remove("retracting");els.beam.style.left=`${x}%`;els.beam.style.top=`${y-11}%`;els.beam.style.height="21%";els.beam.classList.add("active");els.flash.classList.add("active");updateUI();createParticles();playBeam();setTimeout(()=>els.flash.classList.remove("active"),450);
    const distance=item=>Math.hypot((item.x-x)/1.25,item.y-y),inBeam=critters.filter(item=>distance(item)<=CAPTURE_ZONES.beam),caught=[],nearMiss=[],niceCaught=[];inBeam.forEach(item=>{const d=distance(item);if(Math.random()<captureChance(item,d)){caught.push(item);if(d<=CAPTURE_ZONES.center)niceCaught.push(item)}else nearMiss.push(item)});playStats.plays++;if(caught.length)playStats.successes++;else playStats.failures++;if(nearMiss.length)playStats.nearMisses++;caught.forEach(item=>{playStats.counts[item.type.id]=(playStats.counts[item.type.id]||0)+1;playStats.caught.push(createUnitProfile(item.type))});critters.filter(item=>!caught.includes(item)&&!nearMiss.includes(item)).forEach(item=>item.el.classList.add("missed"));nearMiss.forEach((item,index)=>setTimeout(()=>{const sprite=item.el.querySelector(".sprite-art");sprite.style.backgroundImage=`url("${frameUrl(item.type.id,1,true)}")`;item.el.classList.add("near-miss");setTimeout(()=>{item.el.classList.remove("near-miss");sprite.style.backgroundImage=`url("${frameUrl(item.type.id,currentFrame>0?currentFrame:1)}")`},1650)},220+index*70));if(nearMiss.length)setTimeout(()=>tone(185,.28,.035,"triangle"),1120);caught.forEach((item,index)=>setTimeout(()=>{item.el.querySelector(".sprite-art").style.backgroundImage=`url("${frameUrl(item.type.id,1,true)}")`;if(niceCaught.includes(item))item.el.classList.add("nice-catch");item.el.classList.add("abducting");playAnimalVoice(item.type.id)},180+index*90));const retractDelay=caught.length?1680+(caught.length-1)*90:1350,resultDelay=retractDelay+560;setTimeout(()=>els.beam.classList.add("retracting"),retractDelay);const baseGained=caught.reduce((sum,item)=>sum+item.type.score,0),comboMultiplier=Math.max(1,caught.length),gained=baseGained*comboMultiplier,scoreDetail=caught.length>=2?` <span class="bonus">(${baseGained} × ${comboMultiplier})</span>`:"";
    setTimeout(()=>{const previousScore=score;score+=gained;if(gained){animateScore(previousScore,score);playScoreAdd()}caught.forEach(item=>item.el.remove());critters=critters.filter(item=>!caught.includes(item));advancingStage=!critters.length;phase="result";advanceBackground();updateUI();if(advancingStage){showToast(`${caught.length>=2?`<strong class="combo">${caught.length} COMBO!</strong>`:""}${niceCaught.length?"ナイスキャッチした！<br>":""}STAGE ${stage} CLEAR!<br><b>+${gained}</b>${scoreDetail}`);playSuccess();tone(1100,.3,.04,"sine",.35);roundTimer=setTimeout(()=>{if(stage>=10)startEnding();else{stage++;stageUnitCount+=1+Math.floor(Math.random()*6);startStage()}},2600)}else{if(caught.length){const catchMessage=niceCaught.length?"ナイスキャッチした！":"キャッチした！";showToast(`${caught.length>=2?`<strong class="combo">${caught.length} COMBO!</strong>`:""}${caught.map(item=>item.type.name).join("・")}を${catchMessage} <b>+${gained}</b>${scoreDetail}`);playSuccess()}else{showToast("次はキャッチできるよう頑張ろう");tone(160,.3,.04,"triangle")}roundTimer=setTimeout(startRound,2300)}},resultDelay)
  }
  function animate(time){const dt=Math.min((time-previousTime)/1000,.05);previousTime=time;const frameCount=altSpriteMode?3:7,frame=Math.floor(time/128)%frameCount+1;if(frame!==currentFrame){currentFrame=frame;critters.forEach(item=>{if(!item.el.classList.contains("abducting")&&!item.el.classList.contains("near-miss"))item.el.querySelector(".sprite-art").style.backgroundImage=`url("${frameUrl(item.type.id,frame)}")`})}if(phase==="verticalMoving"){y=Math.max(TARGET_BOUNDS.minY,y-20*dt);updatePosition()}else if(phase==="horizontalMoving"){x=Math.min(TARGET_BOUNDS.maxX,x+28*dt);updatePosition()}requestAnimationFrame(animate)}
  function beginControl(){playBGM();if(phase==="vertical"){phase="verticalMoving";tone(390,.08,.025,"square");updateUI()}else if(phase==="horizontal"){phase="horizontalMoving";tone(470,.08,.025,"square");updateUI()}}
  function endControl(){if(phase==="verticalMoving"){phase="horizontal";playDecision();updateUI()}else if(phase==="horizontalMoving"){phase="locked";playDecision();critters.forEach(item=>item.el.classList.toggle("targeted",Math.hypot((item.x-x)/1.25,item.y-y)<=CAPTURE_ZONES.beam));updateUI();setTimeout(fireBeam,280)}}
  document.addEventListener("pointerdown",noteInteraction,{capture:true,passive:true});
  document.addEventListener("keydown",event=>{noteInteraction();if(isUIEvent(event))return;if(event.ctrlKey&&event.key.toLowerCase()==="h"){event.preventDefault();if(!event.repeat)toggleSpawnDebug();return}if(event.ctrlKey&&event.key.toLowerCase()==="c"){event.preventDefault();if(!event.repeat&&!endingMode)startEnding(true);return}if(event.key==="Tab"){event.preventDefault();if(!event.repeat)advanceBackground(true);return}if(event.ctrlKey&&event.key.toLowerCase()==="d"){event.preventDefault();if(!event.repeat)toggleSpriteMode();return}if(event.code!=="Space"||event.repeat)return;event.preventDefault();beginControl()});
  document.addEventListener("keyup",event=>{if(isUIEvent(event)||event.code!=="Space")return;event.preventDefault();endControl()});
  els.game.addEventListener("pointerdown",event=>{if(isUIEvent(event)||event.isPrimary===false||(event.pointerType==="mouse"&&event.button!==0))return;event.preventDefault();playBGM();const touchInput=event.pointerType!=="mouse"||touchMode;if(touchInput){const now=performance.now();if(now-lastTouchInputAt<180)return;lastTouchInputAt=now;if(phase==="vertical"||phase==="horizontal")beginControl();else if(phase==="verticalMoving"||phase==="horizontalMoving")endControl();return}if(pointerActive)return;pointerActive=true;els.game.setPointerCapture?.(event.pointerId);beginControl()});
  els.game.addEventListener("pointerup",event=>{if(event.pointerType!=="mouse"||!pointerActive)return;event.preventDefault();pointerActive=false;endControl()});
  els.game.addEventListener("pointercancel",()=>{pointerActive=false});
  els.game.addEventListener("lostpointercapture",()=>{pointerActive=false});
  ["selectstart","dragstart","contextmenu"].forEach(type=>els.game.addEventListener(type,event=>{if(!isUIEvent(event))event.preventDefault()}));
  els.game.addEventListener("gesturestart",event=>event.preventDefault(),{passive:false});
  [els.bgmToggle,els.seToggle,els.replayCredits,els.restartGame].forEach(button=>button.addEventListener("pointerdown",event=>event.stopPropagation()));
  els.bgmToggle.addEventListener("click",event=>{event.stopPropagation();bgmEnabled=!bgmEnabled;if(bgmEnabled)playBGM();else bgm.pause();updateAudioButtons()});
  bgm.addEventListener("ended",()=>{if(endingMode)return;bgmTrackIndex=(bgmTrackIndex+1)%bgmTracks.length;bgm.src=bgmTracks[bgmTrackIndex].src;updateAudioButtons();playBGM()});
  els.seToggle.addEventListener("click",event=>{event.stopPropagation();seEnabled=!seEnabled;if(!seEnabled){activeAnimalSounds.forEach(sound=>{sound.pause();sound.currentTime=0});activeAnimalSounds.clear()}updateAudioButtons()});
  els.creditsRoll.addEventListener("animationend",event=>{if(event.animationName==="creditsScroll")els.endingActions.classList.add("show")});
  els.replayCredits.addEventListener("click",event=>{event.stopPropagation();replayCredits()});
  els.restartGame.addEventListener("click",event=>{event.stopPropagation();restartGame()});
  els.startButton.classList.add("hidden");els.game.classList.add("alt-sprites");els.controlKey.textContent=touchMode?"TAP":"SPACE / CLICK";ufoFloat.style.backgroundImage='url("assets/characters/frames/ufo-1.png")';updateAudioButtons();renderBackground();startStage();preloadActiveSpriteFrames();previousTime=performance.now();requestAnimationFrame(animate);
  setInterval(advanceIdleBackground,1000);
})();
